name: Checkout and NuGet Restore

on:
  push:
    branches:
      - main

jobs:
  checkout-branches:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Checkout branch1
        uses: actions/checkout@v2
        with:
          ref: branch1

      - name: NuGet Restore for branch1
        run: nuget restore

      - name: Build and Publish branch1
        run: |
          dotnet build --configuration Release
          dotnet publish --configuration Release --output ./publish/branch1
          ls /home/runner/work/Multibranches-dotnet/Multibranches-dotnet/publish/branch2
      
      - name: Checkout branch2
        uses: actions/checkout@v2
        with:
          ref: branch2

      - name: NuGet Restore for branch2
        run: nuget restore
      
      - name: Build and Publish branch2
        run: |
          dotnet build --configuration Release
          dotnet publish --configuration Release --output ./publish/branch2
          ls /home/runner/work/Multibranches-dotnet/Multibranches-dotnet/publish/branch2
