name: Checkout and NuGet Restore

on:
  push:
    branches:
      - main

jobs:
  checkout-branches:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      
      
      - name: Checkout branch2
        uses: actions/checkout@v2
        with:
          ref: branch2

      - name: NuGet Restore for branch2
        run: nuget restore
