name: Checkout and NuGet Restore

on:
  push:
    branches:
      - main
    
jobs:
  checkout-branches:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Checkout branch1
        uses: actions/checkout@v2
        with:
          ref: branch1

      - name: NuGet Restore for branch1
        run: nuget restore

      - name: Build and Publish branch1
        run: |
          dotnet build --configuration Release
          dotnet publish --configuration Release --output ./publish/branch1
          ls ./publish/branch1
      
      - name: Checkout branch2
        uses: actions/checkout@v2
        with:
          ref: branch2

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build and Publish
        run: |
           dotnet publish FirstWebApp.sln --configuration Release --output ./publish/branch2
           ls ./publish
           echo "inside wwwroot"
           echo "<html><body><h1>ASP.NET GitHub Pages Example</h1></body></html>" > ./publish/branch2/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: gh-pages
          folder: ./publish/branch2
