name: Checkout and NuGet Restore

on:
  push:
    branches:
      - main
    
jobs:
  checkout-branches:
    runs-on: windows-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Download .NET Framework Developer Pack
        run: |
          $url = 'https://download.microsoft.com/download/6/E/3/6E3A4E89-5F2D-4A4A-9A3A-BB5652E92C2E/NDP461-DevPack-KB3105179-ENU.exe'
          $path = "$env:TEMP\NDP461-DevPack-KB3105179-ENU.exe"
          Invoke-WebRequest -Uri $url -OutFile $path

      - name: Install .NET Framework Developer Pack
        run: |
          $path = "$env:TEMP\NDP461-DevPack-KB3105179-ENU.exe"
          Start-Process -FilePath $path -ArgumentList '/q' -Wait
      - name: Checkout branch1
        uses: actions/checkout@v2
        with:
          ref: branch1
      

      - name: NuGet Restore for branch1
        run: nuget restore

      - name: Build and Publish branch1
        run: |
          dotnet build --configuration Release
          dotnet publish --configuration Release --output ./publish/branch1
          ls ./publish/branch1
      - name: Upload branch2 Artifact
        uses: actions/upload-artifact@v2
        with:
          name: branch1-artifact
          path: ./publish/branch1
      
      - name: Checkout branch2
        uses: actions/checkout@v2
        with:
          ref: branch2

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build and Publish
        run: |
           dotnet publish FirstWebApp.sln --configuration Release --output ./publish/branch2
           ls ./publish
           echo "inside wwwroot"
           echo "<html><body><h1>ASP.NET GitHub Pages Example</h1></body></html>" > ./publish/branch2/index.html
      - name: Configure Git
        run: |
          git config --global user.name "chandrupsj22"
          git config --global user.email "133023965+chandru-kloudping@users.noreply.github.com"
      - name: Upload branch2 Artifact
        uses: actions/upload-artifact@v2
        with:
          name: branch2-artifact
          path: ./publish/branch2
        
