name: Checkout and NuGet Restore

on:
  push:
    branches:
      - main
  
jobs:
  checkout-branches:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Checkout branch1
        uses: actions/checkout@v2
        with:
          ref: branch1

      - name: NuGet Restore for branch1
        run: nuget restore

      - name: Build and Publish branch1
        run: |
          dotnet build --configuration Release
          dotnet publish --configuration Release --output ./publish/branch1
          ls /home/runner/work/Multibranches-dotnet/Multibranches-dotnet/publish/branch1
      
      - name: Checkout branch2
        uses: actions/checkout@v2
        with:
          ref: branch2

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build and Publish
        run: |
           dotnet publish FirstWebApp.sln --configuration Release --output ./publish
           ls ./publish
           echo "inside wwwroot"
           ls ./publish/wwwroot
           echo "<html><body><h1>ASP.NET GitHub Pages Example</h1></body></html>" > ./publish/index.html

      - name: Configure Git
        run: |
          git config --global user.name "chandrupsj22"
          git config --global user.email "133023965+chandru-kloudping@users.noreply.github.com"
      - name: Checkout branch2
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          
      - name: Commit and push to gh-pages branch
        run: |
          
          git --work-tree=./publish add --all
          git --work-tree=./publish commit -m "Publish to GitHub Pages"
          git push origin HEAD:gh-pages --force

      - name: Switch back to main branch
        run: git checkout main
